from datetime import timedelta

SECRET_KEY = "fc4891f6bc93c26c4a3a106ffeca5bb2"
SQLALCHEMY_DATABASE_URI = "sqlite:///test.db"
SESSION_COOKIE_HTTPONLY = True

JWT_SECRET_KEY = SECRET_KEY
JWT_ACCESS_TOKEN_EXPIRE = timedelta(hours=1)
JWT_REFRESH_TOKEN_EXPIRE = timedelta(days=1)
JWT_TOKEN_LOCATION = ["headers","cookies"]
JWT_SESSION_COOKIE = False
JWT_ACCESS_COOKIE_NAME = "access_token"
JWT_REFRESH_COOKIE_NAME = "refresh_token"
JWT_REFRESH_CSRF_HEADER_NAME = "X-CSRF-REFRESH"
JWT_ACCESS_CSRF_HEADER_NAME = "X-CSRF-ACCESS"