services:
  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - 5000:5000
    depends_on:
      db:
        condition:
          service_healthy
    environment:
      - DATABASE_URI=mysql+pymysql://root:${MYSQL_ROOT_PASSWORD}@db/${MYSQL_DATABASE}
      - SECRET_KEY=${FLASK_SECRET_KEY}
      - PORT=5000
      - FRONT_DOMAIN=frontend
      - FRONT_PORT=80
    networks:
      - app-network
  
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - 80:80
    depends_on:
      - backend
    environment:
      - API_DOMAIN=backend
      - API_PORT=5000
    networks:
      - app-network

  db:
    image: mysql:latest
    restart: always
    container_name: db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: