services:
  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - ./.env
    environment:
      - DATABASE_URI=mysql://root:${MYSQL_ROOT_PASSWORD}@db/${MYSQL_DATABASE}
      - SECRET_KEY=${FLASK_SECRET_KEY}
      - PORT=${FLASK_PORT}
    networks:
      - app-network
  
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - 3000:80
    depends_on:
      - backend
    env_file:
      - ./.env
    environment:
      - API_PROTOCOL=http
      - API_DOMAIN=backend
      - API_PORT=${FLASK_PORT}
    networks:
      - app-network

  db:
    image: mysql:latest
    container_name: db
    env_file:
      - ./.env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge