"""course price added

Revision ID: f392128d744b
Revises: b3458086d2e7
Create Date: 2025-01-30 19:35:56.931714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f392128d744b'
down_revision = 'b3458086d2e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.DECIMAL(precision=3), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
